server:
    port: 8081

spring:
    application:
        name: m1-8001

eureka:
    client:
        register-with-eureka: true # 注册到注册中心
        fetch-registry: true # 从注册中心抓取已有的注册信息
        service-url:
            defaultZone: http://127.0.0.1:7001/eureka/ # eureka server，eureka.client.service-url.defaultZone 属性的值