server:
    port: 8001

spring:
    application:
        name: gateway
    cloud:
        gateway:
            routes: # 路由列表
                - id: m6
                  uri: http://127.0.0.1:6006
                  predicates:
                      - Path=/user/**

                - id: m6a # 路由id
                  uri: http://127.0.0.1:6006  # 路由的uri
                  predicates: # 路由的断言，可以有多个
                      - Path=/fun1

                - id: m5
                  uri: http://127.0.0.1:6005
                  predicates:
                      - Path=/foo

                - id: m6b
                  uri: http://127.0.0.1:6006
                  predicates:
                      - Path=/foo

                - id: test
                  uri: https://www.csdn.net/
                  predicates:
                      - Path=/pp

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://127.0.0.1:7001/eureka