server:
    port: 8082

spring:
    application:
        name: m2-copy-8082

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://127.0.0.1:7001/eureka/