server:
    port: 8082

spring:
    application:
        name: m3-8082
    cloud:
        consul:
            host: 172.20.10.8 # consul服务所在的主机
            port: 8500 # consul服务端口
            discovery:
                service-name: ${spring.application.name} # 配置这个实实例在 consul 上的 "serviceId"